services:
  backend:
    build:
      context: backend
      target: dev-envs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - db-password
    depends_on:

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - backend
